### ISSUE TITLE
Download instructions do not work

### ISSUE THREAD

**Issue by doubleo2** [eo/bluetooth-state-view#1]
Adding `eo.view:bluetoothstate` to a project causes the build to fail because gradle is unable to resolve its transitive dependencies - the dependencies appear to have been renamed.

```
eo.view:bluetoothstate:1.1.0
+--- eo.avd:avd-connecting:1.1.0 FAILED
+--- eo.avd:avd-searching:1.1.0 FAILED
+--- eo.avd:avd-turningonoff:1.1.0 FAILED
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.11 -> 1.3.30 (*)
\--- androidx.appcompat:appcompat:1.0.2 (*)
```

Resolving the transitive dependencies manually does not work either because the dependencies of those dependencies have not been uploaded to jcenter.

```
+--- eo.avd:bluetoothconnecting:1.1.0
|    +--- bluetooth-state-view:vd-connected:unspecified FAILED
|    \--- androidx.appcompat:appcompat:1.0.2 (*)
+--- eo.avd:bluetoothsearching:1.1.0
|    +--- bluetooth-state-view:vd-search:unspecified FAILED
|    \--- androidx.appcompat:appcompat:1.0.2 (*)
+--- eo.avd:bluetoothturningonoff:1.1.0
|    +--- bluetooth-state-view:vd-onoff:unspecified FAILED
|    \--- androidx.appcompat:appcompat:1.0.2 (*)
```

**Comment by eo** [comment]
Thanks for reporting this. I will try to fix it today.

**Comment by eo** [comment]
I fixed the issue. Waiting for JCenter to add vector drawable modules. Then I can test and close this. I will let you know once they are added to JCenter.

**Comment by eo** [comment]
@doubleo2 Could you please test v1.1.1?

**Comment by doubleo2** [comment]
Works like a charm. Thanks

**Comment by eo** [comment]
Glad to hear that. Thanks for reporting :)

**Comment by Vatsal-1501** [comment]
i cannot use this repo it shows me
Failed to resolve: com.github.eo:bluetooth-state-view:1.1.1
Show in Project Structure dialog
Show Details
Affected Modules: app
